package com.mycompany.dao;
// Generated 23/04/2020 11:07:28 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private Integer artCod;
     private Categoria categoria;
     private String artNom;
     private String artUni;
     private BigDecimal artPre;
     private Integer artStk;
     private Integer vista;
     private Set<FacDeta> facDetas = new HashSet<FacDeta>(0);

    public Articulos() {
    }

	
    public Articulos(Categoria categoria) {
        this.categoria = categoria;
    }
    public Articulos(Categoria categoria, String artNom, String artUni, BigDecimal artPre, Integer artStk, Integer vista, Set<FacDeta> facDetas) {
       this.categoria = categoria;
       this.artNom = artNom;
       this.artUni = artUni;
       this.artPre = artPre;
       this.artStk = artStk;
       this.vista = vista;
       this.facDetas = facDetas;
    }
   
    public Integer getArtCod() {
        return this.artCod;
    }
    
    public void setArtCod(Integer artCod) {
        this.artCod = artCod;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getArtNom() {
        return this.artNom;
    }
    
    public void setArtNom(String artNom) {
        this.artNom = artNom;
    }
    public String getArtUni() {
        return this.artUni;
    }
    
    public void setArtUni(String artUni) {
        this.artUni = artUni;
    }
    public BigDecimal getArtPre() {
        return this.artPre;
    }
    
    public void setArtPre(BigDecimal artPre) {
        this.artPre = artPre;
    }
    public Integer getArtStk() {
        return this.artStk;
    }
    
    public void setArtStk(Integer artStk) {
        this.artStk = artStk;
    }
    public Integer getVista() {
        return this.vista;
    }
    
    public void setVista(Integer vista) {
        this.vista = vista;
    }
    public Set<FacDeta> getFacDetas() {
        return this.facDetas;
    }
    
    public void setFacDetas(Set<FacDeta> facDetas) {
        this.facDetas = facDetas;
    }




}


