package com.mycompany.dao;
// Generated 23/04/2020 11:07:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer catCod;
     private String catDes;
     private Integer vista;
     private Set<Articulos> articuloses = new HashSet<Articulos>(0);

    public Categoria() {
    }

	
    public Categoria(String catDes) {
        this.catDes = catDes;
    }
    public Categoria(String catDes, Integer vista, Set<Articulos> articuloses) {
       this.catDes = catDes;
       this.vista = vista;
       this.articuloses = articuloses;
    }
   
    public Integer getCatCod() {
        return this.catCod;
    }
    
    public void setCatCod(Integer catCod) {
        this.catCod = catCod;
    }
    public String getCatDes() {
        return this.catDes;
    }
    
    public void setCatDes(String catDes) {
        this.catDes = catDes;
    }
    public Integer getVista() {
        return this.vista;
    }
    
    public void setVista(Integer vista) {
        this.vista = vista;
    }
    public Set<Articulos> getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set<Articulos> articuloses) {
        this.articuloses = articuloses;
    }




}


