package com.mycompany.dao;
// Generated 23/04/2020 11:07:28 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FacCabe generated by hbm2java
 */
public class FacCabe  implements java.io.Serializable {


     private Integer facNum;
     private Clientes clientes;
     private Vendedor vendedor;
     private String facFec;
     private Character facTipo;
     private int facEst;
     private BigDecimal facSubt;
     private BigDecimal facIgv;
     private BigDecimal facTot;
     private Integer vista;
     private Set<FacDeta> facDetas = new HashSet<FacDeta>(0);

    public FacCabe() {
    }

	
    public FacCabe(int facEst) {
        this.facEst = facEst;
    }
    public FacCabe(Clientes clientes, Vendedor vendedor, String facFec, Character facTipo, int facEst, BigDecimal facSubt, BigDecimal facIgv, BigDecimal facTot, Integer vista, Set<FacDeta> facDetas) {
       this.clientes = clientes;
       this.vendedor = vendedor;
       this.facFec = facFec;
       this.facTipo = facTipo;
       this.facEst = facEst;
       this.facSubt = facSubt;
       this.facIgv = facIgv;
       this.facTot = facTot;
       this.vista = vista;
       this.facDetas = facDetas;
    }
   
    public Integer getFacNum() {
        return this.facNum;
    }
    
    public void setFacNum(Integer facNum) {
        this.facNum = facNum;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Vendedor getVendedor() {
        return this.vendedor;
    }
    
    public void setVendedor(Vendedor vendedor) {
        this.vendedor = vendedor;
    }
    public String getFacFec() {
        return this.facFec;
    }
    
    public void setFacFec(String facFec) {
        this.facFec = facFec;
    }
    public Character getFacTipo() {
        return this.facTipo;
    }
    
    public void setFacTipo(Character facTipo) {
        this.facTipo = facTipo;
    }
    public int getFacEst() {
        return this.facEst;
    }
    
    public void setFacEst(int facEst) {
        this.facEst = facEst;
    }
    public BigDecimal getFacSubt() {
        return this.facSubt;
    }
    
    public void setFacSubt(BigDecimal facSubt) {
        this.facSubt = facSubt;
    }
    public BigDecimal getFacIgv() {
        return this.facIgv;
    }
    
    public void setFacIgv(BigDecimal facIgv) {
        this.facIgv = facIgv;
    }
    public BigDecimal getFacTot() {
        return this.facTot;
    }
    
    public void setFacTot(BigDecimal facTot) {
        this.facTot = facTot;
    }
    public Integer getVista() {
        return this.vista;
    }
    
    public void setVista(Integer vista) {
        this.vista = vista;
    }
    public Set<FacDeta> getFacDetas() {
        return this.facDetas;
    }
    
    public void setFacDetas(Set<FacDeta> facDetas) {
        this.facDetas = facDetas;
    }




}


