package com.mycompany.dao;
// Generated 23/04/2020 11:07:28 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FacDeta generated by hbm2java
 */
public class FacDeta  implements java.io.Serializable {


     private Integer dfacNum;
     private Articulos articulos;
     private FacCabe facCabe;
     private Integer artCan;
     private BigDecimal precioArt;

    public FacDeta() {
    }

	
    public FacDeta(Articulos articulos, FacCabe facCabe) {
        this.articulos = articulos;
        this.facCabe = facCabe;
    }
    public FacDeta(Articulos articulos, FacCabe facCabe, Integer artCan, BigDecimal precioArt) {
       this.articulos = articulos;
       this.facCabe = facCabe;
       this.artCan = artCan;
       this.precioArt = precioArt;
    }
   
    public Integer getDfacNum() {
        return this.dfacNum;
    }
    
    public void setDfacNum(Integer dfacNum) {
        this.dfacNum = dfacNum;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public FacCabe getFacCabe() {
        return this.facCabe;
    }
    
    public void setFacCabe(FacCabe facCabe) {
        this.facCabe = facCabe;
    }
    public Integer getArtCan() {
        return this.artCan;
    }
    
    public void setArtCan(Integer artCan) {
        this.artCan = artCan;
    }
    public BigDecimal getPrecioArt() {
        return this.precioArt;
    }
    
    public void setPrecioArt(BigDecimal precioArt) {
        this.precioArt = precioArt;
    }




}


