package com.mycompany.dao;
// Generated 23/04/2020 11:07:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer venCod;
     private String venNom;
     private String venApe;
     private String venFnac;
     private String venCel;
     private String venFing;
     private String venLogin;
     private String venClave;
     private Integer vista;
     private Set<FacCabe> facCabes = new HashSet<FacCabe>(0);

    public Vendedor() {
    }

    public Vendedor(String venNom, String venApe, String venFnac, String venCel, String venFing, String venLogin, String venClave, Integer vista, Set<FacCabe> facCabes) {
       this.venNom = venNom;
       this.venApe = venApe;
       this.venFnac = venFnac;
       this.venCel = venCel;
       this.venFing = venFing;
       this.venLogin = venLogin;
       this.venClave = venClave;
       this.vista = vista;
       this.facCabes = facCabes;
    }
   
    public Integer getVenCod() {
        return this.venCod;
    }
    
    public void setVenCod(Integer venCod) {
        this.venCod = venCod;
    }
    public String getVenNom() {
        return this.venNom;
    }
    
    public void setVenNom(String venNom) {
        this.venNom = venNom;
    }
    public String getVenApe() {
        return this.venApe;
    }
    
    public void setVenApe(String venApe) {
        this.venApe = venApe;
    }
    public String getVenFnac() {
        return this.venFnac;
    }
    
    public void setVenFnac(String venFnac) {
        this.venFnac = venFnac;
    }
    public String getVenCel() {
        return this.venCel;
    }
    
    public void setVenCel(String venCel) {
        this.venCel = venCel;
    }
    public String getVenFing() {
        return this.venFing;
    }
    
    public void setVenFing(String venFing) {
        this.venFing = venFing;
    }
    public String getVenLogin() {
        return this.venLogin;
    }
    
    public void setVenLogin(String venLogin) {
        this.venLogin = venLogin;
    }
    public String getVenClave() {
        return this.venClave;
    }
    
    public void setVenClave(String venClave) {
        this.venClave = venClave;
    }
    public Integer getVista() {
        return this.vista;
    }
    
    public void setVista(Integer vista) {
        this.vista = vista;
    }
    public Set<FacCabe> getFacCabes() {
        return this.facCabes;
    }
    
    public void setFacCabes(Set<FacCabe> facCabes) {
        this.facCabes = facCabes;
    }




}


